In [22]:
# Import libraries

# math library
import numpy as np

# visualization library
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('png2x','pdf')
import matplotlib.pyplot as plt

# machine learning library
from sklearn.linear_model import LinearRegression

# 3d visualization
from mpl_toolkits.mplot3d import axes3d

# computational time
import time

data = np.loadtxt('data/lab01_data2.txt', delimiter=',')
n = (data.shape[0])

In [23]:
print(data.shape)
print(data[:5,:])
print(n)

(47, 3)
[[0.46985 0.6     0.57137]
 [0.3573  0.6     0.47135]
 [0.53595 0.6     0.52722]
 [0.31621 0.4     0.33148]
 [0.66994 0.8     0.7714 ]]
47


In [34]:
def sigmoid(z):
    sigmoid_f = 1 / (1 + np.exp(-z)) #YOUR CODE HERE
    return sigmoid_f

X = np.ones([n,3]) 
X[:,1:3] = data[:,0:2]
print(X.shape)
print(X[:5,:])


# parameters vector
w = np.array([0.2,-0.4,0.1])[:,None] # [:,None] adds a singleton dimension
print(w.shape)


# predictive function definition
def f_pred(X,w): 
    p = sigmoid(X.dot(w)) #YOUR CODE HERE
    return p


# Test predicitive function 
y_pred = f_pred(X,w)
print(y_pred[:3])

(47, 3)
[[1.      0.46985 0.6    ]
 [1.      0.3573  0.6    ]
 [1.      0.53595 0.6    ]
 [1.      0.31621 0.4    ]
 [1.      0.66994 0.8    ]]
(3, 1)
[[0.51800721]
 [0.52923661]
 [0.51140302]]


In [32]:
y_pred2 = (1 / (1 + np.exp(-47)))*np.array([[1,0.2,0.6]]).dot(w_init)
print('Probability of admission is',y_pred2[0])

Probability of admission is [0.18]


In [28]:
def loss_logreg(y_pred,y): 
    n = len(y)
    loss = -1/n* ( y.T.dot(np.log(y_pred)) + (1-y).T.dot(np.log(1-y_pred)) ) #YOUR CODE HERE
    return loss


# Test loss function 
y = data[:,2][:,None] # label 
print(y.shape)
#print(y)
y_pred = f_pred(X,w) # prediction
loss = loss_logreg(y_pred,y)
print(loss)

(47, 1)
[[0.70512913]]


In [20]:
# gradient function definition
def grad_loss(y_pred,y,X):
    n = len(y)
    grad = 2/n* X.T.dot(y_pred-y) #YOUR CODE HERE
    return grad


# Test grad function 
y_pred = f_pred(X,w)
grad = grad_loss(y_pred,y,X)
print(grad)

[[ 0.06954591]
 [-0.02740689]
 [ 0.01873215]]


In [38]:
def loss_logreg2(y_pred,y, X, w): 
    n = len(y)
    loss = 1/n* np.abs(f_pred(X,w)-y) #YOUR CODE HERE
    return loss


def grad_desc(X, y , w_init=np.array([0,0,0])[:,None] ,tau=1e-4, max_iter=500):

    L_iters = np.zeros([max_iter]) # record the loss values
    w_iters = np.zeros([max_iter,2]) # record the loss values
    w = w_init # initialization
    for i in range(max_iter): # loop over the iterations
        y_pred = f_pred(X,w) # linear predicition function  #YOUR CODE HERE
        grad_f = grad_loss(y_pred,y,X) # gradient of the loss #YOUR CODE HERE
        w = w - tau* grad_f # update rule of gradient descent #YOUR CODE HERE
        L_iters[i] = 1/n* np.abs(f_pred(X,w)-y) # save the current loss value 
        w_iters[i,:] = w[0],w[1] # save the current w value 
        
    return w, L_iters, w_iters


# run gradient descent algorithm
start = time.time()
w_init = np.array([0.2,-0.4,0.1])[:,None]
#w_init = np.array([0,0,0])[:,None]
tau = 0.1; max_iter = 200
w, L_iters, w_iters = grad_desc(X,y,w_init,tau,max_iter)
print('Time=',time.time() - start)
print(L_iters[-1])
print(w)


# plot
plt.figure(3)
plt.plot(np.array(range(max_iter)), L_iters)
plt.xlabel('Iterations')
plt.ylabel('Loss value')
plt.show()

ValueError: setting an array element with a sequence.

In [35]:
def grad_desc2(X, y , w_init=np.array([0,0,0])[:,None] ,tau=1e-4, max_iter=500):

    L_iters = np.zeros([max_iter]) # record the loss values
    w_iters = np.zeros([max_iter,2]) # record the loss values
    w = w_init # initialization
    for i in range(max_iter): # loop over the iterations
        y_pred = f_pred(X,w) # linear predicition function  #YOUR CODE HERE
        grad_f = grad_loss(y_pred,y,X) # gradient of the loss #YOUR CODE HERE
        w = w - tau* grad_f # update rule of gradient descent #YOUR CODE HERE
        L_iters[i] = loss_logreg(y_pred,y) # save the current loss value 
        w_iters[i,:] = w[0],w[1] # save the current w value 
        
    return w, L_iters, w_iters

start = time.time()
w_init = np.array([0.2,-0.4,0.1])[:,None]
#w_init = np.array([0,0,0])[:,None]
tau = 0.1; max_iter = 200
w, L_iters, w_iters = grad_desc(X,y,w_init,tau,max_iter)
print('Time=',time.time() - start)
print(L_iters[-1])
print(w)

Time= 0.013224124908447266
0.6809963625600635
[[-0.32435276]
 [ 0.40376063]
 [ 0.20498445]]


In [31]:
print((1 / (1 + np.exp(-47)))*np.array([[1,0.2,0.6]]).dot(w_init))

[[0.18]]
